### PR TITLE
feat: enable running query services in `merged` mode

### PR DESCRIPTION
**Pull request by rish691**
Enable running hypertrace-data-config-service & hypertrace-data-query-service

Discussion on performance: https://github.com/hypertrace/hypertrace/discussions/194

### CODE REVIEW

**Comment by kotharironak** [comment]
@rish691 Can you add a description?

**Comment by rish691** [comment]
> @rish691 Can you add a description?

@kotharironak  using it for some testing

**Review by JBAhire — APPROVED** [review]

**Comment by kotharironak** [comment]
@rish691 Can you add the test result as a GH discussion link here for reference?

**Comment by rish691** [comment]
> @rish691 Can you add the test result as a GH discussion link here for reference?

Done

**Pull request merged**
