### PR TITLE
fix : timestamp issue

### PR DESCRIPTION
**Pull request by sarthak77**
Ref issue : https://github.com/hypertrace/hypertrace/issues/290#event-5237960861

Tested the script on macOS.

### CODE REVIEW

**Comment by jcchavezs** [comment]
I am not sure python is the right language for this, this kind of things shouldn't require devs to have a certain language installed. I see this is a simple case so we could achieve the same using bash instead.

**Review by JBAhire — DISMISSED** [review]
LGTM. You tried it locally right?

**Comment by sarthak77** [comment]
> LGTM. You tried it locally right?

@JBAhire 
Tested individual components (on ios) but not as a whole.

**Comment by JBAhire** [comment]
@sarthak77 , please test e2e once before merging

**Comment by rish691** [comment]
nit: ~iOS~ macOS

**Review by rish691 — DISMISSED** [review]
Merge post verification

**Review by rish691 — APPROVED** [review]

**Pull request merged**
