### PR TITLE
Updated dashboards and readme with new metrics

### PR DESCRIPTION
**Pull request by kotharironak**
## Description
- As part of this PR (https://github.com/hypertrace/gateway-service/pull/78), have refactored few metrics. This PR makes corresponding changes in ReadMe and dashboard.
- Also updated readme and dashboard with newly added ingestion layer metrics

### Testing
Verified locally, see the below screen shots

### Checklist:
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Done

### CODE REVIEW

**Comment by kotharironak** [comment]
The partial screen of grafana dashboard (was running locally) for both query and ingestion metrics
Screenshot 2021-02-07 at 6 10 35 PM
Screenshot 2021-02-07 at 6 10 07 PM
Screenshot 2021-02-07 at 6 11 50 PM

**Review by rish691 — APPROVED** [review]

**Comment by rish691** [comment]
@kotharironak I think you also need to cut a release for gateway service and update charts for it?

**Comment by rish691** [comment]
I see that for gateway service, last release was cut 11 days ago

**Comment by kotharironak** [comment]
@rish691will cut the release for gateway. And after updating submodules, will cut for hypertrace-service. Charts updates should happen as part of the weekly release cycle.

**Pull request merged**
