### PR TITLE
Adds docker-compose file which runs hypertrace with postgres

### PR DESCRIPTION
**Pull request by kotharironak**
## Description
- Adds a new docker-compose file which runs hypertrace with postgres as a document store (a reference  - https://github.com/hypertrace/hypertrace/issues/124)

### Testing
Verified locally by running below commands
- docker-compose -f docker-compose-postgres.yml pull
- docker-compose -f docker-compose-postgres.yml up

### Checklist:
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Refer readme.md file in `docker/postgres` folder.

### CODE REVIEW

**Comment by JBAhire** [comment]
can we add e2e test for this setup as well? current e2e docker tests use mongo. If we can create one one more job which will test postgres docker-compose, that should be good.

**Comment by kotharironak** [comment]
Reference to this - https://github.com/hypertrace/hypertrace/issues/124

**Comment by kotharironak** [comment]
> can we add e2e test for this setup as well? current e2e docker tests use mongo. If we can create one one more job which will test postgres docker-compose, that should be good.

Do we need documentation for this ticket?

**Review by JBAhire — COMMENTED** [review]
I would move this to separate `postgres` directory and add documentation for it there.

**Review by JBAhire — APPROVED** [review]

**Comment by kotharironak** [comment]
> > can we add e2e test for this setup as well? current e2e docker tests use mongo. If we can create one one more job which will test postgres docker-compose, that should be good.
> 
> sure, we can do that.

Done

**Pull request merged**
